services:
  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:${DB_DATA_VOLUME}

  # phpMyAdmin Service (Web Interface for MySQL)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_gui
    restart: always
    ports:
      - "8080:80"
    environment:
      # Tells phpMyAdmin which database service to connect to
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data:
